pipeline {
    agent any

    environment {
        // Use Jenkins credentials plugin for GitHub + DockerHub
        GITHUB_CREDENTIALS = credentials('github-credentials-id')
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials-id')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: "${GITHUB_CREDENTIALS}",
                    url: 'https://github.com/your-username/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh 'pip3 install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh 'pytest --maxfail=1 --disable-warnings -q --junitxml=test-results.xml'
                }
            }
            post {
                always {
                    junit 'messaging_app/test-results.xml'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('messaging_app') {
                    script {
                        sh 'docker build -t your-dockerhub-username/messaging_app_image .'
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withDockerRegistry([ credentialsId: "${DOCKERHUB_CREDENTIALS}", url: '' ]) {
                    sh 'docker push your-dockerhub-username/messaging_app_image'
                }
            }
        }
    }
}
