apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
    version: blue   # switch this to "green" during traffic cutover
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

